name: Build and publish master

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish docker image to docker hub
      uses: elgohr/Publish-Docker-Github-Action@be0a327a5b402db8600d8d2afa83ecc23b2d9a6e
      with:
        name: nikarh/gotromino:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

